#! /usr/bin/env bash
prompt_yn () {
    MSG=${1:-'Proceed?'}
    read -p "$MSG [y/N] " -n 1 -r
    echo ""
    if ! [[ $REPLY =~ ^[Yy]$ ]]; then return 1; fi
}
unlink_res() {
  if [ -L ./result ]; then
    echo "Build is in:"
    readlink result
    unlink result
  fi
}

if [ "$EUID" -ne 0 ]; then
  echo 'Must be run as SUDO'
  exit 5
fi

# Move to the nix-system-cfg-directory
if [ -z ${DOTFILES+x} ]; then
  echo 'Variable $DOTFILES must be set to run this script'
  exit 4
fi
cd $DOTFILES/nix/
# Add system packages such as `nixos-rebuild`
PATH="$PATH:/run/current-system/sw/bin"

# Confirm with the user
if ! prompt_yn 'Build changes?'; then exit 3; fi

echo "-- Storing current config"
rm -rf /tmp/nixconf-restorept/
cp -r /etc/nixos/ /tmp/nixconf-restorept/

echo "-- Writing new config"
rm -rf /etc/nixos/
cp -r src/ /etc/nixos/

echo "------------------------------"
echo "-- Testing config ------------"
echo "------------------------------"

if nixos-rebuild test && prompt_yn 'Switch build?'; then
    # Safe to switch
    echo "------------------------------"
    echo "-- Building config -----------"
    echo "------------------------------"
    nixos-rebuild switch

    unlink_res
else
    # Revert
    echo "------------------------------"
    echo "-- Reverting changes ---------"
    echo "------------------------------"
    rm -rf /etc/nixos/
    cp -r /tmp/nixconf-restorept/ /etc/nixos/

    # The compilation must have failed
    if [ ! -L result ]; then exit 2; fi
    unlink_res
fi

