#! /usr/bin/env bash

cd $(dtfiles-script-dir)

# Signal that we're comming from loader
LOADER="yes"

# Load functions used in script
source ./lib/prompt

# Move to dotfiles root
cd ..

# load script
source ./nix/enix
