#! /usr/bin/env bash

case "$(printf 'unicode\nclass' | rofi -dmenu -p 'FontAwesome')" in
    unicode)
        cat $HOME/.config/rofi/scripts/rofi-fontawesome/unicode-list.txt \
          | rofi -dmenu -markup-rows -columns 6 -p 'FontAwesome' \
          | cut -d\' -f2 \
          | xclip -selection clipboard
        ;;
    class)
        cat $HOME/.config/rofi/scripts/rofi-fontawesome/icon-list.txt \
          | rofi -dmenu -markup-rows -columns 6 -p 'FontAwesome' \
          | cut -d\' -f2 \
          | xclip -selection clipboard
        ;;
    *)
        ;;
esac
