# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [
    ../../../deps/nixpkgs/nixos/modules/installer/scan/not-detected.nix
  ];

  # A weekly health check for the drive.
  services.fstrim.enable = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/83b4cbc0-ef22-483d-a9c1-f60e4b71fca2";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FE55-E48C";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/d24b4ff3-0a6a-4f22-81a6-1d2c1852f16a"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  system.stateVersion = "19.03";
}
