# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ pkgs, ... }:

{
  environment.systemPackages = with pkgs; [
    ## tools
    wget
    # dig (DNS)
    bind
    # VPN
    #wireguard
    #wireguard-tools

    # btrFS
    btrfsProgs

    wirelesstools
    unzip

    ## X11 stuff
    # Graphical screen config utility

    # Remaping keys
    xlibs.xmodmap

    dmenu

    thunderbird
    firefox
  ];
}
